services:
  - type: web
    name: scanbrix-converter-1
    runtime: docker
    plan: starter
    envVars:
      - key: SUPABASE_URL
        sync: false # Tells Render to use the value already in your Dashboard
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
